language: c
os: linux
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="7.1"
    - RACKET_VERSION="7.2"
    - RACKET_VERSION="7.3"
    - RACKET_VERSION="7.4"
    - RACKET_VERSION="7.5"
    - RACKET_VERSION="7.6"
    - RACKET_VERSION="HEAD"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD"

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
 - raco pkg install --auto mlish-lib/
 - raco pkg install --auto mlish-test/

script:
 - raco test --package mlish-lib
 - raco test --package mlish-test
 - raco setup
